import os
import time
import schedule
import EmailModule
from sys import *
from datetime import datetime
import Checksum as module

FilesScanCount = 0
FilesDeleteCount = 0
Output = ""
Scan_Time = ""
Log_Time = ""


def CreateOutput(Dir_Name, Log_Dir="Marvellous"):
    Log_Dir = os.path.join(Dir_Name, Log_Dir)
    if not os.path.exists(Log_Dir):
        os.mkdir(Log_Dir)

    global FilesScanCount, FilesDeleteCount, Output, Scan_Time, Log_Time
    Scan_Time = datetime.now().strftime("%I:%M:%S %p")

    lst, FileScanCnt, FileDeletedCnt = module.DeleteDuplicateFiles(Dir_Name)

    FilesScanCount = FileScanCnt
    FilesDeleteCount = FileDeletedCnt

    Log_Time = time.ctime()
    FileName = Log_Dir + "\Yogesh_log.txt"

    Output = FileName
    data = ""
    fd = open(FileName, "w")
    fd.write("Log of deleted duplicate files, from directory: " + Log_Time + "\n")
    fd.write(data)
    for i in lst:
        fd.write("\n" + "-" * 80)
        fd.write("\n" + str(i))
    fd.close()


def CreateMail(To, FileName, Scan_Time, Log_Time, FileScanCnt, FileDeletedCnt):
    username = "yogeshnichal@gmail.com"
    password = "**** **** **** ****"                                # Google, App Passwords for SMTP
    to = To

    name = To[0:To.rfind('@')]
    name = ''.join(i for i in name if not i.isdigit())

    subject = "This email sent by program about process log report: %s" % Log_Time

    body = ("""\
        <html>
            <body>
               <p>Hello, %s<p>
               <b style="font-size: 1rem; color: #483D8B;"> Python Automation Mail Schedule with Attachment Script.</b>
               <p>Please find attached log file which contains<p>
               <p>Log of deleted duplicate files, from directory.<p>
               <p>Scanning process started at: %s<p>
               <p>Total files scanned: %s<p> 
               <p>Total duplicate files found: %s<p>

               <p>This is autogenerated mail.<p>

               <p>Thanks & Regards,<p>
               <p>Yogesh Prabhu Nichal<p>
            </body>
        </html>
        """
            ) % (name, Scan_Time, FileScanCnt, FileDeletedCnt)

    if EmailModule.is_connected():
        EmailModule.sendmail(username, password, To, FileName, subject, body)


def main():
    print("-------------------------------------Yogesh Prabhu Nichal------------------------------------------")
    print("\nApplication name:", argv[0])

    if len(argv) != 4:
        print("Insufficient number of arguments. Use -h or -u for help.")
        exit()

    if argv[1].lower() == "-h":
        print("This script will traverse the directory and delete all duplicate files from that directory.\n"
              "Script will write name of deleted files into a 'log' file & Log.txt will create into Directory_Name\n"
              "and Mail will send with log file attachment Receiver_Email_id")
        exit()

    if argv[1].lower() == "-u":
        print("Use: Application_Name Directory_Name Interval_Time Receiver_Email_id")
        exit()

    try:
        Dir_Name = argv[1]
        Time_Interval = int(argv[2])
        To_Email = argv[3]

        schedule.every(Time_Interval).minutes.do(lambda: CreateOutput(Dir_Name))
        schedule.every(int(1)).minutes.do(lambda: CreateMail(To_Email, Output, Scan_Time, Log_Time, FilesScanCount, FilesDeleteCount))

        while True:
            schedule.run_pending()
            time.sleep(2)

    except Exception as E:
        print(E)
    finally:
        print("\n--------------------------------------Thank You--------------------------------------")


if __name__ == "__main__":
    main()

    # py Assignment13.py D:\Demo 01 myfriend.nichal@gmail.com